### ISSUE TITLE
Line editing and command history

### ISSUE THREAD

**Issue by simzer** [subogero/szg#4]
It would be good to have a bash like command history browsable via up/down keys.

**Comment by subogero** [comment]
First just start using `readline()`, which adds shell-like like input line-editing. In a second step start using the readline lib's history features too.

**Comment by subogero** [comment]
Using `readline()` has the additional advantage that the lexer always works from string buffers supplied by our custom `YY_INPUT` macro, instead of files. This paves the way for multiple input files and user defined functions.
